title:  "DataConscientious"
description:
author:
  name: "pardhu448"
  twitter: paululele

menu:
- {name: 'About', file: 'about.html'}
- {name: 'Projects', file: 'projects.html'}
- {name: 'Resources', file: 'about.html'}
- {name: 'Blog', file: 'about.html'}
- {name: 'Contact', file: 'about.html'}

social:
- {icon: 'facebook', link: 'https://www.facebook.com'}
- {icon: 'instagram', link: 'https://instagram.com'}
- {icon: 'linkedin', link: 'https://linkedin.com'}

servicesslide:
- {title: 'Scientific Programming', file: 'scientific_prog.md', image: 'code_logo.png'}
- {title: 'Statistical Learning', file : 'data_modelling.md', image: 'DC_logo_v7.png'}
- {title: 'Digital Marketing Design', file: 'digital_marketing.md', image: 'digital_marketing1.png'} 
- {title: 'ML System Design', file: 'machine_learning_system.md', image: 'mlsystem_logo.png'}

homegriditems:
- {title: 'Projects', file: 'projects.html', mintitle: 'On Github', prose: 'Our open source and independent projects.'}
- {title: 'Testimonials', file: 'projects.html', mintitle: 'From clients', prose: 'Comprehensive feedback on past projects.'}
- {title : 'Research', file: 'research.html', mintitle: 'Using open data', prose: 'Our insightful research on different social issues.'}
- {title : 'Blog', file: 'projects.html', mintitle: 'Opinion', prose: 'Interesting stories from people we admire and follow.'}

jsarr:
- {name : 'slideshow_script', file: 'slide_java.js'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
